### ISSUE TITLE
authorize user Piwigo-TranslationTeam

### ISSUE THREAD

**Issue by ddtddt** [persandstrom/SortOrders#3]
Hi :-)

For add your project on https://piwigo.org/translate, can you give acces to user Piwigo-TranslationTeam and say me it's ok ;-)

**Comment by persandstrom** [comment]
You have access now!

**Comment by ddtddt** [comment]
Hi :-)

no acces

in settings / Manage access
invite a collaborator
Piwigo-TranslationTeam

Thanks

**Comment by persandstrom** [comment]
You have status "pending invite" so I guess you have to accept the invitation before accessing the repo. I removed your invitation and invited again, maybe that will trigger some notification for you.

**Comment by ddtddt** [comment]
Thanks it's ok now :-)
